let
    Source = Folder.Files("\\bjfs01\Group\Operations\Operations Excellence\Performance Analysis\Data Model\"),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "\\bjfs01\Group\Operations\Operations Excellence\Performance Analysis\Data Model\Claims Rejection Analysis\Data\")),
    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "ExcelData", each Excel.Workbook([Content])),
    #"Expanded ExcelData" = Table.ExpandTableColumn(#"Added Custom", "ExcelData", {"Name1", "Data", "Item", "Kind", "Hidden1"}, {"Name1", "Data", "Item", "Kind", "Hidden1"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Expanded ExcelData",{"Data"}),
    #"Expanded Data1" = Table.ExpandTableColumn(#"Removed Other Columns", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68"}),
    #"Promoted Headers" = Table.PromoteHeaders(#"Expanded Data1", [PromoteAllScalars=true]),
    AddPeriodDate = Table.AddColumn(#"Promoted Headers", "BATCH PRIOD DATE", each Date.FromText(Text.Start(Text.From([Batch Period]), 4) & "-" & Text.End(Text.From([Batch Period]), 2) & "-01")),
    #"Changed Type" = Table.TransformColumnTypes(AddPeriodDate,{{"STM_ID", Int64.Type}, {"Batch ID", Int64.Type}, {"Batch Type 2", type text}, {"Batch Status", type text}, {"Batch Year", Int64.Type}, {"Claim Submission Type", type text}, {"TPA Batch", type text}, {"Provider Code", Int64.Type}, {"Provider Name", type text}, {"Provider Network", type text}, {"Provider Rank", type text}, {"Provider Practice", type text}, {"Provider Town", type text}, {"Provider Region", type text}, {"Batch Period", Int64.Type}, {"Batch Type", type text}, {"Batch Ref", type text}, {"Received Date", type datetime}, {"Provider Billed", type number}, {"Presented Discount", type number}, {"Presented Deductible", type number}, {"VAT Amount", type number}, {"NET Billed + VAT", type number}, {"NET Billed - VAT", type number}, {"CCU Invoice Count", Int64.Type}, {"A. Appropriateness of Care", type number}, {"B. Technical_Contractual", type number}, {"B.1 Billed Over Agreed Price", type number}, {"B.1 Pricelist Shortfall / Billed Above Contractual /Agreed Pricing", type number}, {"Shortfall Price", type number}, {"C. Policy Compliance", type number}, {"D. Pre-Authorisation", Int64.Type}, {"E.Unwarranted Variations", Int64.Type}, {"H. Pharmacy Benefit Management", type number}, {"Claims Not Received", Int64.Type}, {"Invalid Service Code", type number}, {"Late Submssion", Int64.Type}, {"Discount Difference", type number}, {"Deductible Difference", type number}, {"Pending", type number}, {"Invalid Membership", type number}, {"Difference in Computation", Int64.Type}, {"BATCH Difference", type number}, {"DEDUCTION", type number}, {"Total Shortfall", type number}, {"% Total Shortfall", type number}, {"APPROVED to Pay", type number}, {"% Approved To Pay", type number}, {"Statement Type", type text}, {"Referral Batch", type text}, {"Approved to Pay VAT", type number}, {"Pending VAT", Int64.Type}, {"A. Appropriateness of Care VAT", type number}, {"B. Technical_Contractual VAT", type number}, {"B1. Pricelist Shortfall / Billed Above Contractual / Agreed Prices VAT", type number}, {"C. Policy Compliance VAT", type number}, {"D. Pre-authorization VAT", type number}, {"E. Unwarranted Variations VAT", Int64.Type}, {"Batch Difference VAT", type number}, {"Late Submission VAT", Int64.Type}, {"Invalid Membership VAT", Int64.Type}, {"Invalid Service Code VAT", type number}, {"Difference in Computation VAT", Int64.Type}, {"Claims not Received VAT", Int64.Type}, {"H. Pharmacy Benefit Management VAT", Int64.Type}, {"DEDUCTION VAT", type number}, {"Deductible Difference VAT", type number}, {"Discount Difference VAT", type number}, {"BATCH PRIOD DATE", type date}}),
    ChangedPeriodType = Table.TransformColumnTypes(#"Changed Type",{{"BATCH PRIOD DATE", type date}}),
    Replace1 = Table.ReplaceValue(ChangedPeriodType,"N","NON TPA",Replacer.ReplaceText,{"TPA Batch"}),
    Replace2 = Table.ReplaceValue(Replace1,"Y","TPA",Replacer.ReplaceText,{"TPA Batch"}),
    Replace3 = Table.ReplaceValue(Replace2,"I","INITIAL",Replacer.ReplaceText,{"Statement Type"}),
    Replace4 = Table.ReplaceValue(Replace3,"R","REWORK",Replacer.ReplaceText,{"Statement Type"}),
    Replace5 = Table.ReplaceValue(Replace4,"N","NON-REFERRAL",Replacer.ReplaceText,{"Referral Batch"}),
    Replace6 = Table.ReplaceValue(Replace5,"Y","REFERRAL",Replacer.ReplaceText,{"Referral Batch"}),
    Replace7 = Table.ReplaceValue(Replace6,"a. Top 20","Non-Government",Replacer.ReplaceText,{"Provider Rank"}),
    Replace8 = Table.ReplaceValue(Replace7, "b. Top 50", "Non-Government", Replacer.ReplaceText, {"Provider Rank"}),
    Replace9 = Table.ReplaceValue(Replace8, "c. Top 100", "Non-Government", Replacer.ReplaceText, {"Provider Rank"}),
    Replace10 = Table.ReplaceValue(Replace9, "d. Above 100", "Non-Government", Replacer.ReplaceText, {"Provider Rank"}),
    Replace11 = Table.ReplaceValue(Replace10, "e. Inactive", "Non-Government", Replacer.ReplaceText, {"Provider Rank"}),
    Replace12 = Table.ReplaceValue(Replace11, "e. Private - POA", "Non-Government", Replacer.ReplaceText, {"Provider Rank"}),
    Replace13 = Table.ReplaceValue(Replace12, "e. Special Arrangement", "Non-Government", Replacer.ReplaceText, {"Provider Rank"}),
    Replace14 = Table.ReplaceValue(Replace13, "e. Governmental", "Government", Replacer.ReplaceText, {"Provider Rank"}),
    #"Removed Columns" = Table.RemoveColumns(Replace14,{"Approved to Pay VAT", "Pending VAT", "D. Pre-authorization VAT", "C. Policy Compliance VAT", "B1. Pricelist Shortfall / Billed Above Contractual / Agreed Prices VAT", "E. Unwarranted Variations VAT", "Batch Difference VAT", "A. Appropriateness of Care VAT", "Late Submission VAT", "B. Technical_Contractual VAT", "Invalid Membership VAT", "Invalid Service Code VAT", "Difference in Computation VAT", "Claims not Received VAT", "H. Pharmacy Benefit Management VAT", "DEDUCTION VAT", "Deductible Difference VAT", "Discount Difference VAT"}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"STM_ID", "Batch ID", "Batch Type 2", "Batch Status", "Batch Year", "Claim Submission Type", "TPA Batch", "Provider Code", "Provider Name", "Provider Network", "Provider Rank", "Provider Practice", "Provider Town", "Provider Region", "Batch Period", "Batch Type", "Batch Ref", "Received Date", "Provider Billed", "NET Billed + VAT","Referral Batch","BATCH PRIOD DATE","Statement Type"}, "Attribute", "Value"),
    #"Filtered Rows1" = Table.SelectRows(#"Unpivoted Other Columns", each true),
    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each true),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows2",{{"Attribute", "Billing Cat"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Value", type number}})
in
    #"Changed Type1"
