
select "CL_BATCH_HEADER4"."NOTES", "CL_BATCH_HEADER4"."RCV_DATE", trim(both
 from "PV_PROVIDER5"."PROV_CODE"), "CL_BATCH_HEADER4"."CLM_SUBMISSION_TYPE", "CL_BATCH_HEADER4"."BATCH_ID", "CL_BATCH_HEADER4"."BATCH_STATUS_DESC", "CL_BATCH_HEADER4"."PERIOD", "CL_BATCH_HEADER4"."TPA", case  when "CL_BATCH_HEADER4"."CLM_SUBMISSION_TYPE" in ('Nphies', 'DHS', 'Direct Integration') then 'INTEGRATION' else 'NON-INTEGRATION' end , (nvl("CL_BATCH_HEADER4"."BILL_PRESENT_AMT", 0) - nvl("CL_BATCH_HEADER4"."BILL_DISC_AMT", 0)) - nvl("CL_BATCH_HEADER4"."BILL_DEDUCT_AMT", 0), "CL_BATCH_HEADER4"."VAT_AMT"
 from (
select "CL_BATCH_HEADER"."BATCH_ID", "CL_BATCH_HEADER"."PROV_CODE", "CL_BATCH_HEADER"."RCV_DATE", "CL_BATCH_HEADER"."PERIOD", "CL_BATCH_HEADER"."BILL_PRESENT_AMT", "CL_BATCH_HEADER"."BILL_DISC_AMT", "CL_BATCH_HEADER"."BILL_DEDUCT_AMT", "CL_BATCH_HEADER"."NOTES", "CL_BATCH_HEADER"."VAT_AMT", "SY_STATUS_BATCH_HEADER"."EDESC" "BATCH_STATUS_DESC", "SYS_SUBMIS_TYPE"."EDESC" "CLM_SUBMISSION_TYPE", "CL_BATCH_HEADER"."TPA"
 from ("CSR"."CL_BATCH_HEADER" "CL_BATCH_HEADER" INNER JOIN "CSR"."SY_STATUS_BATCH_HEADER" "SY_STATUS_BATCH_HEADER" on "CL_BATCH_HEADER"."STATUS"="SY_STATUS_BATCH_HEADER"."SYS_CODE") LEFT OUTER JOIN "CSR"."SY_SYS_CODE" "SYS_SUBMIS_TYPE" on "CL_BATCH_HEADER"."CLM_SUBMIS_TYPE"="SYS_SUBMIS_TYPE"."SYS_CODE" and 'CLM_SUBMISSION_TYPE'="SYS_SUBMIS_TYPE"."SYS_TYPE") "CL_BATCH_HEADER4", (
select "PV_PROVIDER"."PROV_CODE"
 from (((((("CSR"."PV_PROVIDER" "PV_PROVIDER" INNER JOIN "CSR"."DC_DISTRICT" "DC_DISTRICT" on "PV_PROVIDER"."CORR_DIST_CODE"="DC_DISTRICT"."DIST_CODE") LEFT OUTER JOIN "CSR"."SY_PROVIDER_LEVEL" "SY_PROVIDER_LEVEL1" on "PV_PROVIDER"."PROV_LEVEL"="SY_PROVIDER_LEVEL1"."SYS_CODE") LEFT OUTER JOIN "CSR"."SY_PRACTICE_TYPE" "SY_PRACTICE_TYPE" on "PV_PROVIDER"."PRACTICE_TYPE"="SY_PRACTICE_TYPE"."SYS_CODE") LEFT OUTER JOIN "CSR"."PV_PROV_LVL_MVMNT" on "PV_PROVIDER"."PROV_CODE"="PV_PROV_LVL_MVMNT"."PROV_CODE") LEFT OUTER JOIN "CSR"."SY_PROVIDER_LEVEL" "SY_PROVIDER_LEVEL2" on "PV_PROV_LVL_MVMNT"."PROV_LEVEL"="SY_PROVIDER_LEVEL2"."SYS_CODE") LEFT OUTER JOIN "CSR"."SY_SYS_CODE" "VRS" on "PV_PROVIDER"."VAT_REG_STATUS"=trim(both
 from "VRS"."SYS_CODE") and 'VAT_REG_STATUS'=trim(both
 from "VRS"."SYS_TYPE")) LEFT OUTER JOIN "CSR"."SY_SYS_CODE" "CTC" on "PV_PROVIDER"."CTRY_CODE"=trim(both
 from "CTC"."SYS_CODE") and 'COUNTRY_CODE'=trim(both
 from "CTC"."SYS_TYPE")
 where "PV_PROV_LVL_MVMNT"."END_DATE" is null and "PV_PROVIDER"."PRACTICE_TYPE"<>280) "PV_PROVIDER5"
 where "CL_BATCH_HEADER4"."PROV_CODE"="PV_PROVIDER5"."PROV_CODE" and "CL_BATCH_HEADER4"."BATCH_STATUS_DESC"<>'Rework' and "CL_BATCH_HEADER4"."RCV_DATE"<=TRUNC( CURRENT_DATE ) and "CL_BATCH_HEADER4"."RCV_DATE">=DATE '2025-01-01'

select "PAYMENT11"."Payment_Date" "c0", "PAYMENT11"."BATCH_HEADER" "c1"
 from (
select max(case  when "BF_CLM_PAYMENT6"."PAY_METHOD"='AT' then "BF_CLM_PAYMENT6"."EFT_DATE" else "BF_CLM_PAYMENT6"."CHQ_DATE" end ) "Payment_Date", "BF_CLM_PAYMENT6"."BATCH_ID" "BATCH_HEADER"
 from (((
select "CL_BATCH_HEADER"."BATCH_ID", "CL_BATCH_HEADER"."RCV_DATE", "CL_BATCH_HEADER"."PERIOD"
 from ("CSR"."CL_BATCH_HEADER" "CL_BATCH_HEADER" INNER JOIN "CSR"."SY_STATUS_BATCH_HEADER" "SY_STATUS_BATCH_HEADER" on "CL_BATCH_HEADER"."STATUS"="SY_STATUS_BATCH_HEADER"."SYS_CODE") LEFT OUTER JOIN "CSR"."SY_SYS_CODE" "SYS_SUBMIS_TYPE" on "CL_BATCH_HEADER"."CLM_SUBMIS_TYPE"="SYS_SUBMIS_TYPE"."SYS_CODE" and 'CLM_SUBMISSION_TYPE'="SYS_SUBMIS_TYPE"."SYS_TYPE") "CL_BATCH_HEADER8" LEFT OUTER JOIN (
select *
 from "CSR"."BF_CLM_PAYMENT_V" "BF_CLM_PAYMENT_V"
 where "BF_CLM_PAYMENT_V"."DELETED_IND"='N') "BF_CLM_PAYMENT6" on "CL_BATCH_HEADER8"."BATCH_ID"="BF_CLM_PAYMENT6"."BATCH_ID") LEFT OUTER JOIN (
select "SYS_CODE", "EDESC" "PV_PAY_TYPE"
 from "CSR"."SY_SYS_CODE"
 where "SYS_TYPE"='PAY_TYPE') "SY_PV_PAY_TYPE" on "BF_CLM_PAYMENT6"."PAY_TYPE"="SY_PV_PAY_TYPE"."SYS_CODE") FULL OUTER JOIN (
select *
 from "CSR"."BF_CLM_PAYMENT"
 where "BF_CLM_PAYMENT"."DELETED_IND"='N') "BF_CLM_PAYMENT1" on "BF_CLM_PAYMENT1"."PAY_TYPE"="SY_PV_PAY_TYPE"."SYS_CODE"
 where "SY_PV_PAY_TYPE"."PV_PAY_TYPE"='Prompt Payment' and "CL_BATCH_HEADER8"."PERIOD">='201901' and "CL_BATCH_HEADER8"."RCV_DATE" between DATE '2025-01-01' and TRUNC( CURRENT_DATE ) and "BF_CLM_PAYMENT1"."DELETED_IND"='N'
 group by "BF_CLM_PAYMENT6"."BATCH_ID") "PAYMENT11"
 order by "c1" asc nulls last