with "CL_BATCH_HEADER6" as (
select "CL_BATCH_HEADER"."BATCH_ID", "CL_BATCH_HEADER"."PROV_CODE", "CL_BATCH_HEADER"."RCV_DATE", "CL_BATCH_HEADER"."PERIOD", "CL_BATCH_HEADER"."BILL_PRESENT_AMT", "CL_BATCH_HEADER"."BILL_DISC_AMT", "CL_BATCH_HEADER"."BILL_DEDUCT_AMT", "CL_BATCH_HEADER"."CRT_DATE", "CL_BATCH_HEADER"."NOTES", "CL_BATCH_HEADER"."UN_HOLD_DATE", "CL_BATCH_HEADER"."VAT_AMT", "CL_BATCH_HEADER"."HOLD_REASON", "SY_STATUS_BATCH_HEADER"."EDESC" "BATCH_STATUS_DESC", "SYS_SUBMIS_TYPE"."EDESC" "CLM_SUBMISSION_TYPE", "CL_BATCH_HEADER"."TPA"
 from ("CSR"."CL_BATCH_HEADER" "CL_BATCH_HEADER" INNER JOIN "CSR"."SY_STATUS_BATCH_HEADER" "SY_STATUS_BATCH_HEADER" on "CL_BATCH_HEADER"."STATUS"="SY_STATUS_BATCH_HEADER"."SYS_CODE") LEFT OUTER JOIN "CSR"."SY_SYS_CODE" "SYS_SUBMIS_TYPE" on "CL_BATCH_HEADER"."CLM_SUBMIS_TYPE"="SYS_SUBMIS_TYPE"."SYS_CODE" and 'CLM_SUBMISSION_TYPE'="SYS_SUBMIS_TYPE"."SYS_TYPE"), "PV_PROVIDER7" as (
select "PV_PROVIDER"."PROV_CODE", "PV_PROVIDER"."PROV_NAME", "PV_PROVIDER"."CORR_DIST_CODE", "PV_PROVIDER"."RELATIONS"
 from (((((("CSR"."PV_PROVIDER" "PV_PROVIDER" INNER JOIN "CSR"."DC_DISTRICT" "DC_DISTRICT" on "PV_PROVIDER"."CORR_DIST_CODE"="DC_DISTRICT"."DIST_CODE") LEFT OUTER JOIN "CSR"."SY_PROVIDER_LEVEL" "SY_PROVIDER_LEVEL1" on "PV_PROVIDER"."PROV_LEVEL"="SY_PROVIDER_LEVEL1"."SYS_CODE") LEFT OUTER JOIN "CSR"."SY_PRACTICE_TYPE" "SY_PRACTICE_TYPE" on "PV_PROVIDER"."PRACTICE_TYPE"="SY_PRACTICE_TYPE"."SYS_CODE") LEFT OUTER JOIN "CSR"."PV_PROV_LVL_MVMNT" on "PV_PROVIDER"."PROV_CODE"="PV_PROV_LVL_MVMNT"."PROV_CODE") LEFT OUTER JOIN "CSR"."SY_PROVIDER_LEVEL" "SY_PROVIDER_LEVEL2" on "PV_PROV_LVL_MVMNT"."PROV_LEVEL"="SY_PROVIDER_LEVEL2"."SYS_CODE") LEFT OUTER JOIN "CSR"."SY_SYS_CODE" "VRS" on "PV_PROVIDER"."VAT_REG_STATUS"=trim(both
 from "VRS"."SYS_CODE") and 'VAT_REG_STATUS'=trim(both
 from "VRS"."SYS_TYPE")) LEFT OUTER JOIN "CSR"."SY_SYS_CODE" "CTC" on "PV_PROVIDER"."CTRY_CODE"=trim(both
 from "CTC"."SYS_CODE") and 'COUNTRY_CODE'=trim(both
 from "CTC"."SYS_TYPE")
 where "PV_PROV_LVL_MVMNT"."END_DATE" is null and "PV_PROVIDER"."PRACTICE_TYPE"<>280), "SY_PROVIDER_LOCATION" as (
select "DC_DISTRICT"."DIST_CODE", "DC_DISTRICT"."EDESC" "TOWN", "DC_DISTRICT"."AREA_CODE"
 from "CSR"."DC_DISTRICT" "DC_DISTRICT"), "SY_PROVIDER_LOCATION8" as (
select "SY_PROVIDER_LOCATION"."DIST_CODE" "DIST_CODE", case  when "SY_PROVIDER_LOCATION"."AREA_CODE"='W' then 'a. Western Region' when "SY_PROVIDER_LOCATION"."AREA_CODE"='C' then 'b. Central Region' when "SY_PROVIDER_LOCATION"."AREA_CODE"='E' then 'c. Eastern Region' when "SY_PROVIDER_LOCATION"."AREA_CODE"='N' then 'd. Northern Region' when "SY_PROVIDER_LOCATION"."AREA_CODE"='S' then 'e. Southern Region' else 'f. Overseas' end  "REGION"
 from "SY_PROVIDER_LOCATION"), "Batch_Header13" as (
select "CL_BATCH_HEADER6"."BATCH_ID" "Batch_ID", "CL_BATCH_HEADER6"."PERIOD" "Batch_Period", substr("CL_BATCH_HEADER6"."PERIOD", 1, 4) "Batch_Year", "CL_BATCH_HEADER6"."BATCH_STATUS_DESC" "Batch_Status", sum((nvl("CL_BATCH_HEADER6"."BILL_PRESENT_AMT", 0) - nvl("CL_BATCH_HEADER6"."BILL_DISC_AMT", 0)) - nvl("CL_BATCH_HEADER6"."BILL_DEDUCT_AMT", 0)) "PROV_Netbilled", sum("CL_BATCH_HEADER6"."VAT_AMT") "VAT_AMT", "CL_BATCH_HEADER6"."NOTES" "Batch_Notes", "CL_BATCH_HEADER6"."CLM_SUBMISSION_TYPE" "Claim_Submission_Type", "CL_BATCH_HEADER6"."HOLD_REASON" "Hold_Reason", "CL_BATCH_HEADER6"."RCV_DATE" "Batch_Received_Date", "CL_BATCH_HEADER6"."UN_HOLD_DATE" "UnholdDate", trim(both
 from "PV_PROVIDER7"."PROV_CODE") "Provider_Code", "PV_PROVIDER7"."PROV_NAME" "Provider_Name", "SY_PROVIDER_LOCATION8"."REGION" "Provider_Region", "PV_PROVIDER7"."RELATIONS" "Relations", "CL_BATCH_HEADER6"."CRT_DATE" "Create_Date", sum(((nvl("CL_BATCH_HEADER6"."BILL_PRESENT_AMT", 0) - nvl("CL_BATCH_HEADER6"."BILL_DISC_AMT", 0)) - nvl("CL_BATCH_HEADER6"."BILL_DEDUCT_AMT", 0)))+sum("CL_BATCH_HEADER6"."VAT_AMT") "PROV_NB___VAT", "CL_BATCH_HEADER6"."TPA" "TPA_Batch"
 from ("CL_BATCH_HEADER6" INNER JOIN "PV_PROVIDER7" on "CL_BATCH_HEADER6"."PROV_CODE"="PV_PROVIDER7"."PROV_CODE") LEFT OUTER JOIN "SY_PROVIDER_LOCATION8" on "PV_PROVIDER7"."CORR_DIST_CODE"="SY_PROVIDER_LOCATION8"."DIST_CODE"
 where "CL_BATCH_HEADER6"."RCV_DATE" between TIMESTAMP '2025-11-09 00:00:00.000000000' and TIMESTAMP '2025-11-09 00:00:00.000000000'
 group by "CL_BATCH_HEADER6"."BATCH_ID", "CL_BATCH_HEADER6"."PERIOD", substr("CL_BATCH_HEADER6"."PERIOD", 1, 4), "CL_BATCH_HEADER6"."BATCH_STATUS_DESC", "CL_BATCH_HEADER6"."NOTES", "CL_BATCH_HEADER6"."CLM_SUBMISSION_TYPE", "CL_BATCH_HEADER6"."HOLD_REASON", "CL_BATCH_HEADER6"."RCV_DATE", "CL_BATCH_HEADER6"."UN_HOLD_DATE", trim(both
 from "PV_PROVIDER7"."PROV_CODE"), "PV_PROVIDER7"."PROV_NAME", "SY_PROVIDER_LOCATION8"."REGION", "PV_PROVIDER7"."RELATIONS", "CL_BATCH_HEADER6"."CRT_DATE", "CL_BATCH_HEADER6"."TPA"), "CL_BATCH_HEADER11" as (
select "CL_BATCH_HEADER"."BATCH_ID", "CL_BATCH_HEADER"."PERIOD"
 from ("CSR"."CL_BATCH_HEADER" "CL_BATCH_HEADER" INNER JOIN "CSR"."SY_STATUS_BATCH_HEADER" "SY_STATUS_BATCH_HEADER" on "CL_BATCH_HEADER"."STATUS"="SY_STATUS_BATCH_HEADER"."SYS_CODE") LEFT OUTER JOIN "CSR"."SY_SYS_CODE" "SYS_SUBMIS_TYPE" on "CL_BATCH_HEADER"."CLM_SUBMIS_TYPE"="SYS_SUBMIS_TYPE"."SYS_CODE" and 'CLM_SUBMISSION_TYPE'="SYS_SUBMIS_TYPE"."SYS_TYPE"), "BF_CLM_PAYMENT10" as (
select *
 from "CSR"."BF_CLM_PAYMENT_V" "BF_CLM_PAYMENT_V"
 where "BF_CLM_PAYMENT_V"."DELETED_IND"='N'), "SY_PV_PAY_TYPE" as (
select "SYS_CODE", "EDESC" "PV_PAY_TYPE"
 from "CSR"."SY_SYS_CODE"
 where "SYS_TYPE"='PAY_TYPE'), "BF_CLM_PAYMENT1" as (
select *
 from "CSR"."BF_CLM_PAYMENT"
 where "BF_CLM_PAYMENT"."DELETED_IND"='N'), "Payment14" as (
select distinct "SY_PV_PAY_TYPE"."PV_PAY_TYPE" "Payment_Type", case  when "BF_CLM_PAYMENT10"."PAY_METHOD"='AT' then "BF_CLM_PAYMENT10"."EFT_DATE" else "BF_CLM_PAYMENT10"."CHQ_DATE" end  "Payment_Date", "BF_CLM_PAYMENT10"."BATCH_ID" "BATCH_HEADER", "CL_BATCH_HEADER11"."PERIOD" "Batch_Period"
 from (("CL_BATCH_HEADER11" LEFT OUTER JOIN "BF_CLM_PAYMENT10" on "CL_BATCH_HEADER11"."BATCH_ID"="BF_CLM_PAYMENT10"."BATCH_ID") LEFT OUTER JOIN "SY_PV_PAY_TYPE" on "BF_CLM_PAYMENT10"."PAY_TYPE"="SY_PV_PAY_TYPE"."SYS_CODE") FULL OUTER JOIN "BF_CLM_PAYMENT1" on "BF_CLM_PAYMENT1"."PAY_TYPE"="SY_PV_PAY_TYPE"."SYS_CODE"
 where "SY_PV_PAY_TYPE"."PV_PAY_TYPE"='Prompt Payment' and "CL_BATCH_HEADER11"."PERIOD">='201901' and "BF_CLM_PAYMENT1"."DELETED_IND"='N') 
select "T0"."C0" "Provider_Code", "T0"."C1" "Provider_Name", "T0"."C2" "Claim_Submission_Type", "T0"."C3" "Provider_Region", "T0"."C4" "Batch_ID", "T0"."C5" "Batch_Status", "T0"."C6" "Batch_Period", "T0"."C7" "Batch_Year", "T0"."C8" "UnholdDate", "T0"."C9" "Batch_Received_Date", "T0"."C10" "Payment_Date", "T0"."C11" "Hold_Reason", "T0"."C12" "Batch_Notes", sum("T0"."C13") over (partition by "T0"."C4", "T0"."C6", "T0"."C7", "T0"."C5", "T0"."C12", "T0"."C2", "T0"."C11", "T0"."C9", "T0"."C8", "T0"."C0", "T0"."C1", "T0"."C3", "T0"."C14", "T0"."C15", "T0"."C16") "PROV_Netbilled", "T0"."C17" "Payment_Type", "T0"."C15" "Create_Date", "T0"."C14" "Relations", sum("T0"."C18") over (partition by "T0"."C4", "T0"."C6", "T0"."C7", "T0"."C5", "T0"."C12", "T0"."C2", "T0"."C11", "T0"."C9", "T0"."C8", "T0"."C0", "T0"."C1", "T0"."C3", "T0"."C14", "T0"."C15", "T0"."C16") "PROV_NB___VAT", "T0"."C16" "TPA_Batch"
 from (
select "Batch_Header13"."Provider_Code" "C0", "Batch_Header13"."Provider_Name" "C1", "Batch_Header13"."Claim_Submission_Type" "C2", "Batch_Header13"."Provider_Region" "C3", "Batch_Header13"."Batch_ID" "C4", "Batch_Header13"."Batch_Status" "C5", "Batch_Header13"."Batch_Period" "C6", "Batch_Header13"."Batch_Year" "C7", "Batch_Header13"."UnholdDate" "C8", "Batch_Header13"."Batch_Received_Date" "C9", "Payment14"."Payment_Date" "C10", "Batch_Header13"."Hold_Reason" "C11", "Batch_Header13"."Batch_Notes" "C12", sum("Batch_Header13"."PROV_Netbilled") "C13", "Batch_Header13"."Relations" "C14", "Batch_Header13"."Create_Date" "C15", "Batch_Header13"."TPA_Batch" "C16", "Payment14"."Payment_Type" "C17", sum("Batch_Header13"."PROV_NB___VAT") "C18"
 from "Batch_Header13" LEFT OUTER JOIN "Payment14" on "Batch_Header13"."Batch_ID"="Payment14"."BATCH_HEADER"
 group by "Batch_Header13"."Provider_Code", "Batch_Header13"."Provider_Name", "Batch_Header13"."Claim_Submission_Type", "Batch_Header13"."Provider_Region", "Batch_Header13"."Batch_ID", "Batch_Header13"."Batch_Status", "Batch_Header13"."Batch_Period", "Batch_Header13"."Batch_Year", "Batch_Header13"."UnholdDate", "Batch_Header13"."Batch_Received_Date", "Payment14"."Payment_Date", "Batch_Header13"."Hold_Reason", "Batch_Header13"."Batch_Notes", "Payment14"."Payment_Type", "Batch_Header13"."Create_Date", "Batch_Header13"."Relations", "Batch_Header13"."TPA_Batch") "T0"
