with "CL_BATCH_HEADER4" as (
select "CL_BATCH_HEADER"."BATCH_ID", "CL_BATCH_HEADER"."PERIOD"
 from ("CSR"."CL_BATCH_HEADER" "CL_BATCH_HEADER" INNER JOIN "CSR"."SY_STATUS_BATCH_HEADER" "SY_STATUS_BATCH_HEADER" on "CL_BATCH_HEADER"."STATUS"="SY_STATUS_BATCH_HEADER"."SYS_CODE") LEFT OUTER JOIN "CSR"."SY_SYS_CODE" "SYS_SUBMIS_TYPE" on "CL_BATCH_HEADER"."CLM_SUBMIS_TYPE"="SYS_SUBMIS_TYPE"."SYS_CODE" and 'CLM_SUBMISSION_TYPE'="SYS_SUBMIS_TYPE"."SYS_TYPE"), "BF_CLM_PAYMENT3" as (
select *
 from "CSR"."BF_CLM_PAYMENT_V" "BF_CLM_PAYMENT_V"
 where "BF_CLM_PAYMENT_V"."DELETED_IND"='N'), "SY_PV_PAY_TYPE" as (
select "SYS_CODE", "EDESC" "PV_PAY_TYPE"
 from "CSR"."SY_SYS_CODE"
 where "SYS_TYPE"='PAY_TYPE'), "BF_CLM_PAYMENT1" as (
select *
 from "CSR"."BF_CLM_PAYMENT"
 where "BF_CLM_PAYMENT"."DELETED_IND"='N') 
select distinct "SY_PV_PAY_TYPE"."PV_PAY_TYPE" "Payment_Type", case  when "BF_CLM_PAYMENT3"."PAY_METHOD"='AT' then "BF_CLM_PAYMENT3"."EFT_DATE" else "BF_CLM_PAYMENT3"."CHQ_DATE" end  "Payment_Date", "BF_CLM_PAYMENT3"."BATCH_ID" "BATCH_HEADER", "CL_BATCH_HEADER4"."PERIOD" "Batch_Period"
 from (("CL_BATCH_HEADER4" LEFT OUTER JOIN "BF_CLM_PAYMENT3" on "CL_BATCH_HEADER4"."BATCH_ID"="BF_CLM_PAYMENT3"."BATCH_ID") LEFT OUTER JOIN "SY_PV_PAY_TYPE" on "BF_CLM_PAYMENT3"."PAY_TYPE"="SY_PV_PAY_TYPE"."SYS_CODE") FULL OUTER JOIN "BF_CLM_PAYMENT1" on "BF_CLM_PAYMENT1"."PAY_TYPE"="SY_PV_PAY_TYPE"."SYS_CODE"
 where "SY_PV_PAY_TYPE"."PV_PAY_TYPE"='Prompt Payment' and "CL_BATCH_HEADER4"."PERIOD">='201901' and "BF_CLM_PAYMENT1"."DELETED_IND"='N'
